/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#2563eb',
        'on-background': '#0b1c30',
        outline: '#737686',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary-fixed': '#2a1700',
        'tertiary-fixed-dim': '#ffb95f',
        'primary-fixed': '#dbe1ff',
        'on-surface-variant': '#434655',
        'on-secondary': '#ffffff',
        'inverse-surface': '#213145',
        'secondary-container': '#6cf8bb',
        'on-primary-fixed': '#00174b',
        'surface-container': '#e5eeff',
        'outline-variant': '#c3c6d7',
        'on-primary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        background: '#f8f9ff',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'surface-tint': '#0053db',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#996100',
        primary: '#004ac6',
        'on-error': '#ffffff',
        tertiary: '#784b00',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-fixed-variant': '#003ea8',
        'surface-variant': '#d3e4fe',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffddb8',
        'on-surface': '#0b1c30',
        'on-secondary-fixed': '#002113',
        'surface-dim': '#cbdbf5',
        secondary: '#006c49',
        'on-tertiary-container': '#ffeedd',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-fixed': '#6ffbbe',
        'on-primary-container': '#eeefff',
        'surface-container-low': '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-secondary-container': '#00714d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gap-xs': '4px',
        'gap-sm': '8px',
        'gap-md': '16px',
        'gap-lg': '24px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'label-caps': ['Work Sans', 'sans-serif'],
        'input-text': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'input-text': ['20px', { lineHeight: '24px', fontWeight: '500' }],
      },
      animation: {
        'pulse-border': 'pulse-border 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-up': 'slide-up 0.3s ease-out',
      },
      keyframes: {
        'pulse-border': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '0.8' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
