/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        glass: {
          DEFAULT: 'rgba(255, 255, 255, 0.05)',
          light: 'rgba(255, 255, 255, 0.08)',
          medium: 'rgba(255, 255, 255, 0.12)',
          border: 'rgba(255, 255, 255, 0.12)',
          'border-light': 'rgba(255, 255, 255, 0.06)',
        },
        dark: {
          bg: '#0a0a14',
          surface: '#12121f',
          'surface-elevated': '#1a1a2e',
          border: '#2a2a3e',
          text: '#e8e8f0',
          'text-muted': '#9898b0',
          accent: '#6c5ce7',
          'accent-hover': '#7c6df7',
          secondary: '#00cec9',
          tertiary: '#fd79a8',
        },
        primary: {
          DEFAULT: '#6c5ce7',
          hover: '#7c6df7',
          light: '#8b7cf7',
          dark: '#5b4bd6',
          container: 'rgba(108, 92, 231, 0.15)',
        },
        secondary: {
          DEFAULT: '#00cec9',
          hover: '#00e0db',
          container: 'rgba(0, 206, 201, 0.15)',
        },
        accent: {
          DEFAULT: '#fd79a8',
          hover: '#fe8db6',
          container: 'rgba(253, 121, 168, 0.15)',
        },
        surface: '#12121f',
        'surface-elevated': '#1a1a2e',
        background: '#0a0a14',
        'on-background': '#e8e8f0',
        'on-surface': '#e8e8f0',
        'on-surface-variant': '#9898b0',
        outline: '#3a3a4e',
        'outline-variant': '#2a2a3e',
        'surface-container': '#161625',
        'surface-container-high': '#1c1c30',
        'surface-container-lowest': '#0e0e1a',
        error: '#ff6b6b',
        'error-container': 'rgba(255, 107, 107, 0.15)',
        success: '#00cec9',
        'success-container': 'rgba(0, 206, 201, 0.15)',
        warning: '#fdcb6e',
        'warning-container': 'rgba(253, 203, 110, 0.15)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'gap-xs': '4px',
        'gap-sm': '8px',
        'gap-md': '16px',
        'gap-lg': '24px',
        'gap-xl': '32px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'heading-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'heading-md': ['22px', { lineHeight: '30px', fontWeight: '700' }],
        'heading-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
        'fade-in-down': 'fadeInDown 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite linear',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(108, 92, 231, 0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(108, 92, 231, 0.3)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
